=== mcjo79/Blue-Reflection-Quartet-Uncensor-Restore-Translation-Unburger-Mod/Blue_Reflection_Text_Tool/translation_fr.dtd
<!--
  Shared schema for the French translation files of the BLUE REFLECTION games.

  The translation is split into one file per category, each a standalone
  <translation> document conforming to this DTD:

    * names.xml    - character / creature names (chara, monster, race);
    * places.xml   - location names (school map, field map, library);
    * items.xml    - object / crafting names (items, treasure, fragments, costumes);
    * dialogue.xml - the event dialogue, grouped by <chapter> (one per event
                     folder, e.g. "aa01" prologue, "ce01" chapter 1, ...);
    * other.xml    - every remaining string (UI, battle, tutorial, NPC messages,
                     missions, ...).

  Text content is plain UTF-8.  Inline control sequences (for example "<CR>"
  for a line break) appear as literal text and are escaped as XML entities.

  msg_id and name_id are decimal unsigned 32-bit integers; 4294967295
  (0xFFFFFFFF) means "no identifier".  string_no is the game's String_No key.
-->
<!ELEMENT translation (meta?, names?, places?, items?, messages?, dialogue?, other?)>
<!ATTLIST translation
    game  CDATA #REQUIRED
    lang  CDATA #REQUIRED
>

<!ELEMENT meta EMPTY>
<!ATTLIST meta
    release        CDATA #IMPLIED
    version        CDATA #IMPLIED
    source         CDATA #IMPLIED
    generated_utc  CDATA #IMPLIED
>

<!ELEMENT names (string*)>
<!ELEMENT places (string*)>
<!ELEMENT items (string*)>
<!ELEMENT messages (string*)>
<!ELEMENT other (string*)>

<!ELEMENT string (#PCDATA)>
<!ATTLIST string
    string_no  CDATA #REQUIRED
>

<!ELEMENT dialogue (chapter*)>
<!ELEMENT chapter (event*)>
<!ATTLIST chapter
    id  CDATA #REQUIRED
>

<!ELEMENT event (message*)>
<!ATTLIST event
    file  CDATA #REQUIRED
>

<!ELEMENT message (#PCDATA)>
<!ATTLIST message
    msg_id   CDATA #IMPLIED
    name_id  CDATA #IMPLIED
>

=== mcjo79/Blue-Reflection-Quartet-Uncensor-Restore-Translation-Unburger-Mod/titles/blue_reflection/translation_fr/places.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE translation SYSTEM "../../../Blue_Reflection_Text_Tool/translation_fr.dtd">
<translation game="blue_reflection" lang="fr">
    <meta release="Blue Reflection French Translation 8 1.1 2026-08-21T07-02Z YUzj5sMpX" generated_utc="2026-10-14T01:48:14Z" />
    <places>
        <string string_no="2228225">Ecole</string>
        <string string_no="2228226">Maison</string>
        <string string_no="2228227">Evénement</string>
        <string string_no="2228228">Common central</string>
        <string string_no="2228229">Zone de joie</string>
        <string string_no="2228230">Zone de peur</string>
        <string string_no="2228231">Zone de tristesse</string>
        <string string_no="2228232">Zone de colere</string>
        <string string_no="2228233">Zone de joie et de peur</string>
        <string string_no="2228234">Zone de peur et de tristesse</string>
        <string string_no="2228235">Zone de tristesse et de colere</string>
        <string string_no="2228236">Zone de colere et de joie</string>
        <string string_no="3735553" />
        <string string_no="3735554" />
        <string string_no="3735555" />
        <string string_no="3735556" />
        <string string_no="3735557" />
        <string string_no="3735558" />
        <string string_no="3735559" />
        <string string_no="3735560" />
        <string string_no="3735561" />
        <string string_no="3735562" />
        <string string_no="3735563" />
        <string string_no="3735564" />
        <string string_no="3735565" />
        <string string_no="3735566" />
        <string string_no="3735567" />
        <string string_no="3735568" />
        <string string_no="3735569" />
        <string string_no="3735570" />
        <string string_no="3735571" />
        <string string_no="3735572" />
        <string string_no="3735573" />
        <string string_no="3735574" />
        <string string_no="3735575" />
        <string string_no="3735576" />
        <string string_no="3735577" />
        <string string_no="3735578" />
        <string string_no="3735579" />
        <string string_no="3735580" />
        <string string_no="3735581" />
        <string string_no="3735582" />
        <string string_no="3735583" />
        <string string_no="3735584" />
        <string string_no="3735585" />
        <string string_no="3735586" />
        <string string_no="3735587" />
        <string string_no="3735588" />
        <string string_no="3735589" />
        <string string_no="3735590" />
        <string string_no="3735591" />
        <string string_no="3735592" />
        <string string_no="4980737">Batiment scolaire</string>
        <string string_no="4980738">Toit</string>
        <string string_no="4980739">Toit</string>
        <string string_no="4980740">Local du club de sciences</string>
        <string string_no="4980741">3e étage</string>
        <string string_no="4980742">Couloir du 3e étage</string>
        <string string_no="4980743">Local du conseil des éleves</string>
        <string string_no="4980744">Local du comité du festival</string>
        <string string_no="4980745">3-A</string>
        <string string_no="4980746">3-B</string>
        <string string_no="4980747">2e étage</string>
        <string string_no="4980748">Couloir du 2e étage</string>
        <string string_no="4980749">Bibliotheque</string>
        <string string_no="4980750">Salle des auteurs</string>
        <string string_no="4980751">2-A</string>
        <string string_no="4980752">2-B</string>
        <string string_no="4980753">1er étage</string>
        <string string_no="4980754">Couloir du 1er étage</string>
        <string string_no="4980755">Supérette du lycée</string>
        <string string_no="4980756">1-A</string>
        <string string_no="4980757">1-B</string>
        <string string_no="4980758">Infirmerie</string>
        <string string_no="4980759">Installation</string>
        <string string_no="4980760">Entrée principale</string>
        <string string_no="4980761">Cour</string>
        <string string_no="4980762">Terrain</string>
        <string string_no="4980763">Salon d'essai</string>
        <string string_no="4980764">Autre</string>
        <string string_no="4980765">Accueil</string>
        <string string_no="5046273">Se déplacer dans l'établissement</string>
        <string string_no="5046274">Aller sur le toit</string>
        <string string_no="5046275">Aller sur le toit</string>
        <string string_no="5046276">Aller au local du club de sciences</string>
        <string string_no="5046277">Aller au 3e étage</string>
        <string string_no="5046278">Aller dans le couloir du 3e étage</string>
        <string string_no="5046279">Aller au local du conseil des éleves</string>
        <string string_no="5046280">Aller au local du comité du festival</string>
        <string string_no="5046281">Aller en classe normale 3-A</string>
        <string string_no="5046282">Aller en classe spéciale 3-B</string>
        <string string_no="5046283">Aller au 2e étage</string>
        <string string_no="5046284">Aller dans le couloir du 2e étage</string>
        <string string_no="5046285">Aller a la bibliotheque</string>
        <string string_no="5046286">Aller dans la salle des auteurs</string>
        <string string_no="5046287">Aller en classe normale 2-A</string>
        <string string_no="5046288">Aller en classe spéciale 2-B</string>
        <string string_no="5046289">Aller au 1er étage</string>
        <string string_no="5046290">Aller dans le couloir du 1er étage</string>
        <string string_no="5046291">Aller a la supérette du lycée</string>
        <string string_no="5046292">Aller en classe normale 1-A</string>
        <string string_no="5046293">Aller en classe spéciale 1-B</string>
        <string string_no="5046294">Aller a l'infirmerie</string>
        <string string_no="5046295">Aller vers une installation du lycée</string>
        <string string_no="5046296">Aller a l'entrée principale</string>
        <string string_no="5046297">Aller dans la cour</string>
        <string string_no="5046298">Aller sur le terrain</string>
        <string string_no="5046299">Menu de changement de tenues</string>
        <string string_no="5046300">Sortir de l'établissement</string>
        <string string_no="5046301">Rentrer chez soi</string>
    </places>
</translation>

=== mcjo79/Blue-Reflection-Quartet-Uncensor-Restore-Translation-Unburger-Mod/titles/second_light/translation_fr/dialogue_16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE translation SYSTEM "../../../Blue_Reflection_Text_Tool/translation_fr.dtd">
<translation game="second_light" lang="fr"><meta release="BRSL beta dialogue + machine translation" /><dialogue><chapter id="zz00"><event file="event_en/zz00/event_message_zz00_010.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_020.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_030.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_040.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_050.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_060.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_070.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_080.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_090.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_100.ebm"><message msg_id="0" name_id="0">Ordre du jour 1&lt;CR&gt;A propos de la structure</message><message msg_id="1" name_id="3">La structure qui se trouvait dans mon Heartscape...&lt;CR&gt;Je pense toujours que c'est la clé.</message><message msg_id="2" name_id="3">Qu'en avez-vous toutes pensé ?</message><message msg_id="3" name_id="0">La structure a été placée la par une mystérieuse tierce partie&lt;CR&gt;comme indice pour sauver Oasis.</message></event><event file="event_en/zz00/event_message_zz00_110.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_120.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_130.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_140.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_150.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_160.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_170.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_180.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_190.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_200.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_210.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_220.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_230.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_240.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_250.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_260.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_270.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_280.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_290.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_300.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_310.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_320.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_330.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_340.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_350.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_360.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_370.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_380.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_390.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_400.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_410.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_420.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_430.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_440.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_450.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_460.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_470.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_480.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_490.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event><event file="event_en/zz00/event_message_zz00_500.ebm"><message msg_id="4294967295" name_id="4294967295">徃纃宁</message></event></chapter></dialogue></translation>

=== mcjo79/Blue-Reflection-Quartet-Uncensor-Restore-Translation-Unburger-Mod/titles/second_light/translation_fr/places.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE translation SYSTEM "../../../Blue_Reflection_Text_Tool/translation_fr.dtd">
<translation game="second_light" lang="fr"><meta release="BRSL beta system text (mojibake fixed) + machine translation for gaps" /><places><string string_no="2228236">Coeurite d’Ao</string><string string_no="2228237">Route vers l’Origine</string><string string_no="2228227">Coeurite de Shiho</string><string string_no="2228231">Coeurite de Kirara</string><string string_no="2228234">Coeurite de Yuzu et Lime</string><string string_no="2228228">Coeurite d’Uta</string><string string_no="2228229">Coeurite de Hinako</string><string string_no="2228226">Le Forlointain</string><string string_no="2228233">Coeurite de Yuki</string><string string_no="2228238" /><string string_no="2228241">Ile lointaine</string><string string_no="2228242">Coeurite de Ryza</string><string string_no="2228232">Coeurite des s. Hirahara</string><string string_no="2228240" /><string string_no="2228230">Coeurite de Rena</string><string string_no="2228243">Coeurite inconnue</string><string string_no="2228244" /><string string_no="2228235" /><string string_no="2228225">Ecole</string><string string_no="2228245" /><string string_no="2228239">Coeurite de Kokoro</string></places></translation>
